apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: data-volume
          mountPath: /usr/share/nginx/html  # Mounts on this directory inside the pod
  volumes:
    - name: data-volume
      hostPath:
        path: /data  # The directory on the host
        type: DirectoryOrCreate  # Create the directory if it doesn't exist
