apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx  # This should match the label of your pod
  ports:
    - port: 80          # The port that will be exposed on the service
      targetPort: 80    # The port on the pod
      nodePort: 30000    # Optional: specify a NodePort; Kubernetes will automatically assign one if omitted

