apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
  - name: my-container
    image: nginx
    env:
    - name: SIMPLE_KEY1
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: SIMPLE_KEY1
    - name: SIMPLE_KEY2
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: SIMPLE_KEY2
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:

      name: my-config
      items:
      - key: config-file-1
        path: config-file-1.txt
      - key: config-file-2
        path: config-file-2.txt
